name: Esquio Docker UI Continous Deployment
on: 
  push:
    tags:       
      - ui-release-*  # Push events to release-* 
env:
  TAG: 4.0.0
  IMAGE_NAME: esquioui
  ESQUIO_REPO: xabarilcoding
jobs:  
  docker_build_publish:    
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: ${{ env.ESQUIO_REPO }}/${{ env.IMAGE_NAME }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ./build/UIDockerfile
        tags: "latest,${{ env.TAG }}"